source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JCTagListView_Example', :exclusive => true do
  pod "JCTagListView", :path => "../"
end

target 'JCTagListView_Tests', :exclusive => true do
  pod "JCTagListView", :path => "../"

  
end
