source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCTagListView_Example' do
  pod "JCTagListView", :path => "../"
end

target 'JCTagListView_Tests' do
  pod "JCTagListView", :path => "../"
end
